name: deploy
on:
  pull_request_target:
    types: closed
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: np-complete/publish-book-action@v1
